language: c
script:
  - echo "yes" | sudo add-apt-repository ppa:avsm/ocaml42+opam12
  - sudo apt-get update -qq
  - sudo apt-get install -qq opam ocaml-native-compilers
  - export OPAMYES=1
  - opam init
  - eval `opam config env`
  - opam pin add -n -k path ppx_deriving .
  - opam install --deps-only -d -t ppx_deriving
  - opam install -d -t -v ppx_deriving
