language: c
script:
  #- echo "yes" | sudo add-apt-repository ppa:avsm/ppa-opam-experimental
  - echo 'deb http://download.opensuse.org/repositories/home:/ocaml/Debian_7.0/ /' | sudo tee /etc/apt/sources.list
  - curl -L http://download.opensuse.org/repositories/home:ocaml/Debian_7.0/Release.key | sudo apt-key add -
  - sudo apt-get update -qq
  - sudo apt-get install -qq opam #ocaml-native-compilers
  - export OPAMYES=1
  - opam init --comp=4.02.0+trunk
  - eval `opam config env`
  - opam pin add -n -k path ppx_deriving .
  - opam install --deps-only -d -t ppx_deriving
  - opam install -d -t -v ppx_deriving
